# Change these first
owner: fabiuslabs # Your GitHub username
repo: internal-health-check  # Your GitHub repository name

# Add your sites here
sites:
  - name: Fabius Labs
    url: https://fabiuslabs.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://assets-global.website-files.com/643d308e0069813dbe7c79f3/64652de0e115e4ac4b49906d_fabuis-labs-logo-yellow.svg
  name: Fabius Labs Health Checker
  introTitle: "Web application health monitor"
  introMessage: "Monitoring for all Fabius Labs and associated web applications"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
